### PR TITLE
Generate a random free port for sauce connect when managing sauce connect identifiers

### PR DESCRIPTION
**Pull request by halkeye**

### CODE REVIEW

**Comment by apemberton** [comment]
Hi: I would recommend using something like the https://wiki.jenkins-ci.org/display/JENKINS/Port+Allocator+Plugin as opposed to generating a random port for this need. https://github.com/jenkinsci/sauce-ondemand-plugin/pull/10 made that possible.

**Comment by theCampbell** [comment]
Hi @apemberton ,
#10 will work yes but it involves installing a new plugin, which would require review and acceptance by our mutual friend so I am shying away from it as an immediate option.  Either way should work correct?  Or is there some larger issue to this design decision that I am not seeing?

Cheers,
Andrew

**Comment by halkeye** [comment]
Also this is an additional feature it doesn't stop #10 from working

**Comment by apemberton** [comment]
Seems both options should work, so didn't mean to imply this was a bad design by any means. My thought about our mutual friend is that usually enterprise networks are locked down enough that random ports might work for things talking on the inside, but anything that needs to talk from the outside is better to use a named set as with Port Allocator.

**Comment by theCampbell** [comment]
@apemberton , no worries and that is still a very valid point.  I think the best bet is to implement both and let the user choose as I see both avenues being valid for users long term.

**Pull request merged**
