### PR TITLE
Don't blindly cast to AbstractProject

### PR DESCRIPTION
**Pull request by rsandell**
There can be other Item types like WorkflowJob
that can cause ClassCastException.

@reviewbybees

### CODE REVIEW

**Comment by jtnord** [comment]
:bee: as it stops the CCEx but does it actually need the AbstractBuild to begin with?

**Comment by halkeye** [comment]
I actualy don't think the file is needed at all. It was part of an attempt to get username into the axis, and I don't think I intended it to be committed.

**Comment by jglick** [comment]
:bee: as a hotfix. For actual Pipeline compatibility, `SauceOnDemandBuildWrapper` would need to become a `SimpleBuildWrapper`, and set environment variables within its scope rather than using `SauceCredentialsEnvironmentContributor`.

**Comment by halkeye** [comment]
I think I'll end up just deleting the file. I'm just about to take off to
sf so I can't test till I've landed

**Comment by halkeye** [comment]
@rsandell @jglick @jtnord 

Is there a way to reproduce this? I am trying a new pipeline build with Jenkins ver. 1.642.1, and i don't even see the option to enable sauce labs. When I build the sample hello world app it works just fine.

Is this actually crashing? or just a potential crash?

**Comment by rsandell** [comment]
@halkeye As soon as a pipeline needs to assemble the environment I got the exception thrown.

So for me it happened simply with:
```groovy
node {
  sh 'env | sort'
}

```

**Comment by rsandell** [comment]
@reviewbybees done

**Comment by halkeye** [comment]
Okay, I've removed the file. I'll get a release out asap.
cc @jsmoxon

**Comment by halkeye** [comment]
sauce-ondemand-1.149 is now released

**Pull request closed without merging**
